Repository newrelic/nri-cassandra, pull requests merged in 2019-02, with the labels that each got.

#16 Added license files
  .papers_config.yml
  papers_manifest.yml
Labels: risk:none

#17 Add suffix for selecting yml while packaging
  Makefile-package.mk
Labels: bug

#22 Add dockerfile
  Dockerfile
Labels: risk:low

#23 Fix wrong nrjmx dependency in Dockerfile
  Dockerfile
Labels: risk:none
